### ISSUE TITLE
internal dependency between manage_repo and repo_version

### ISSUE THREAD

**Issue by preflightsiren** [elasticsearch/puppet-logstash#166]
if you just set manage_repo => true, you get a cryptic message about repo_version not being of type StringClass.

It should be clearer either in the readme, or the comments that setting manage_repo => true, requires you to also provide a repo_version.

This could also be fixed by providing a default repo_version.

**Comment by AAlvz** [comment]
Should this issue be closed after the merge? I think it's ready to be closed.

**Comment by igalic** [comment]
@AAlvz if it works, then, yes, definitely close it:)
