### ISSUE TITLE
Should manage the "logstash-web" service

### ISSUE THREAD

**Issue by TJM** [elasticsearch/puppet-logstash#198]
The module should manage the `logstash-web` ... at a minimum:
* bind address
* port
* enabled

**Comment by jordansissel** [comment]
logstash-web was removed a short time ago, so there should soon be no need to manage it.

Related ticket: (on removing logstash-web) https://github.com/elasticsearch/logstash/issues/1797

**Comment by electrical** [comment]
Closing this issue as logstash-web is removed.
